Several improvements based on feedback
digabi/koe-ohje pull request #536
Opened 2022-03-17 12:15 UTC by mplattu

* Allow `input()` calls without parameters
 * Clear error messages even there are no outputs
 * Handle log outputs and allow user to copy output to clipboard
 * Catch and show Pyodide initialisation problems

2022-03-17 12:54 UTC, eeroan requested changes
Pari pikkujuttua vois vielä refaktoroida. Onkohan näille mahdollista edes tehdä testejä?

2022-03-17 12:54 UTC, eeroan commented on src/tabs/programming.ts
> +const isSingleColumn = (): boolean => {
Tää olis kompaktimpi tapa tehdä sama:
```
const isSingleColumn = () => window.innerWidth / 2 <= document.getElementById(codeEditorWrapperId).offsetWidth
```

2022-03-17 12:54 UTC, eeroan commented on src/tabs/programming.ts
> +const getEditorHeight = (): number => {
Ite tykkään yhden statementin funktioissa poistaa return ja aaltosulut:
```
const getEditorHeight = () => document.getElementById(codeEditorWrapperId).offsetHeight
```

2022-03-17 12:54 UTC, eeroan commented on src/tabs/programming.ts
> +  if (isSingleColumn()) {
Tekisin newHight laskemiselle oman funktion, joka saa parametrina currentHeight niin pääsis letistä eroon ja vois käyttää ternarya tai edes iffiä missä suoraan palautetaan arvo. Onko noille magic numbereille mitään järkevää nimeä, jolla ne vois esitellä muuttujissa?

2022-03-17 12:54 UTC, eeroan commented on src/tabs/programming.ts
> +    element.style.height = '0'
tässäkin tekisin funktion, joka palauttaa height-arvon, niin silloin `element.style.height = ` tarvitsee kirjoittaa vain kerran

2022-03-17 12:54 UTC, eeroan commented on src/tabs/common/clipboard.ts
> +  copyableElements.forEach(element => element.addEventListener('click', (event: MouseEvent) => { copyTextContent(event, 'copying_box_kbd') } ))
Click handler riittää määritellä kerran yhteiselle juurielementille, minkä jälkeen handlerissa voidaan tarkistaa event.target.classList.contains('clickable') ja vain silloin kutsua copyTextContent

2022-03-17 12:54 UTC, eeroan commented on src/tabs/common/clipboard.ts
> +  copyableCodeElements.forEach(element => element.addEventListener('click', (event: MouseEvent) => { copyTextContent(event, 'copying_box_code') } ))
sama pätee näihin muihin

2022-03-18 09:35 UTC, mplattu commented on src/tabs/common/clipboard.ts
> +  copyableElements.forEach(element => element.addEventListener('click', (event: MouseEvent) => { copyTextContent(event, 'copying_box_kbd') } ))
Mä muokkasin tätä nyt hiukan, mutta en ihan kuten ehdotat. Olis aika iso duuni käydä lisäämässä HTML:ään yhteinen luokka kaikkiin klikattaviin elementteihin.

2022-03-18 09:59 UTC, mplattu commented on src/tabs/programming.ts
> +const isSingleColumn = (): boolean => {
:+1:

2022-03-18 10:00 UTC, mplattu commented on src/tabs/common/clipboard.ts
> +  copyableCodeElements.forEach(element => element.addEventListener('click', (event: MouseEvent) => { copyTextContent(event, 'copying_box_code') } ))
Ks. yllä.

2022-03-18 10:55 UTC, eeroan commented on src/tabs/common/clipboard.ts
> +  copyableElements.forEach(element => element.addEventListener('click', copyTextContent ))
Tarkotin siis että ton yllä oilevan voi sit vielä korvata tämmösellä:
```
document.body.addEventListener('click', copyTextContent)
```
tai `document.body` tilalla joku tarkempi selektori, jonka alla noi kaikki on, tyyliin `document.querySelector('.myContainer', copyTextContent)`

Näin ollen ei tartte jokaista elementtiä erikseen hakea ja sitten määritellä jokaiselle omaa click-handleria.

2022-03-18 10:55 UTC, eeroan commented on src/tabs/common/clipboard.ts
> +
eli tässä kohtaa sitten poistuttais funktiosta mikäli successElementId on undefined

2022-03-18 10:55 UTC, eeroan commented on src/tabs/programming.ts
> +const setOutputAndErrorHeight = (elementId: string) => {
Siis jotain tämmöstä tarkotin:
```
const calculateHeight = (element: HTMLElement) => {
    const suggestedHeight = getSuggestedOutputAndErrorHeight()
    const contentHeight = element.scrollHeight
    return contentHeight > suggestedHeight ? suggestedHeight : contentHeight + 20
}
const setOutputAndErrorHeight = (elementId: string) => {
    const suggestedHeight = getSuggestedOutputAndErrorHeight()
    const element = document.getElementById(elementId)!
    const setHeight = (newHeight: number) => (element.style.height = newHeight + 'px')

    setHeight(0)
    setHeight(calculateHeight(element))
}
```

2022-03-21 10:36 UTC, merged